# Generated by Django 5.2.3 on 2025-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_finder_app', '0002_video_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
