# Generated by Django 5.2.3 on 2026-01-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_finder_app', '0003_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
